category:
  name:
    maximum_length: 255
carts:
  cookie_expire: 24
comment:
  content:
    min: 4
    max: 300
order_item:
  greater_equal: 1
order:
  greater_equal: 1
product:
  per_page: 15
  min_quantity: 1
  default_quantity: 1
