category:
  name:
    maximum_length: 255
carts:
  cookies_expiry: 24
checkouts:
  cookies_expiry: 24
comment:
  content:
    min: 4
    max: 300
order_item:
  greater_equal: 1
order:
  greater_equal: 1
product:
  per_page: 15
  min_quantity: 1
  default_quantity: 1
recent_viewed_products: 15
recent_products_expiration: 24
domain: "0.0.0.0"
